/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SomewhereOnlyWeKnowRouteImport } from './routes/somewhere-only-we-know'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SomewhereOnlyWeKnowRoute = SomewhereOnlyWeKnowRouteImport.update({
  id: '/somewhere-only-we-know',
  path: '/somewhere-only-we-know',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/somewhere-only-we-know': typeof SomewhereOnlyWeKnowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/somewhere-only-we-know': typeof SomewhereOnlyWeKnowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/somewhere-only-we-know': typeof SomewhereOnlyWeKnowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/somewhere-only-we-know'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/somewhere-only-we-know'
  id: '__root__' | '/' | '/somewhere-only-we-know'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SomewhereOnlyWeKnowRoute: typeof SomewhereOnlyWeKnowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/somewhere-only-we-know': {
      id: '/somewhere-only-we-know'
      path: '/somewhere-only-we-know'
      fullPath: '/somewhere-only-we-know'
      preLoaderRoute: typeof SomewhereOnlyWeKnowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SomewhereOnlyWeKnowRoute: SomewhereOnlyWeKnowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
